[[H2AgModel]]
arch = "x86_64"
git-tree-sha1 = "ac985dcb029a780f174327cf7aeb38c78d8c5028"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[H2AgModel.download]]
    sha256 = "2f862dd462cecbfb3d1fb47a8c0c62097a2279ebbee549ec5067fd751333222f"
    url = "https://github.com/maurergroup/H2AgModel_jll.jl/releases/download/H2AgModel-v0.1.1+0/H2AgModel.v0.1.1.x86_64-linux-gnu-libgfortran3.tar.gz"
[[H2AgModel]]
arch = "x86_64"
git-tree-sha1 = "8f1ce3c6a2f37291769023e770737026cef3dc90"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[H2AgModel.download]]
    sha256 = "55fc5ad812a00872f71629eabf0c46bb81c87fe9db53a8482d1473f692363ce3"
    url = "https://github.com/maurergroup/H2AgModel_jll.jl/releases/download/H2AgModel-v0.1.1+0/H2AgModel.v0.1.1.x86_64-linux-gnu-libgfortran4.tar.gz"
[[H2AgModel]]
arch = "x86_64"
git-tree-sha1 = "04c8ec6676fafb7b3c3a01c98ece2cf285e4055f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[H2AgModel.download]]
    sha256 = "6732398005f466c9bb698bb365da494ec09fb5fa6bce9427353dc9b12c739045"
    url = "https://github.com/maurergroup/H2AgModel_jll.jl/releases/download/H2AgModel-v0.1.1+0/H2AgModel.v0.1.1.x86_64-linux-gnu-libgfortran5.tar.gz"
