# Autogenerated wrapper script for H2AgModel_jll for x86_64-linux-gnu-libgfortran5
export h2ag111_friction, h2ag111_pes

using CompilerSupportLibraries_jll
JLLWrappers.@generate_wrapper_header("H2AgModel")
JLLWrappers.@declare_library_product(h2ag111_friction, "h2ag111_friction.so")
JLLWrappers.@declare_library_product(h2ag111_pes, "h2ag111_pes.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll)
    JLLWrappers.@init_library_product(
        h2ag111_friction,
        "lib/h2ag111_friction.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        h2ag111_pes,
        "lib/h2ag111_pes.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
